Repository GoogleChromeLabs/pwa-wp, pull requests merged in 2022-02, with the labels that each got.

#691 Add short name field in General Settings when Site Title is longer than 12 characters
  tests/test-class-wp-web-app-manifest.php
  wp-includes/class-wp-web-app-manifest.php
Labels: web-app-manifest

#698 Add maskable icon checkbox in customizer settings
  pwa.php
  tests/test-class-wp-customize-manager.php
  tests/test-class-wp-web-app-manifest.php
  wp-admin/js/customize-controls-site-icon-maskable.js
  wp-includes/class-wp-customize-manager.php
  wp-includes/class-wp-web-app-manifest.php
Labels: enhancement

#714 Finish utilizing node-version-file for setup-node GHA
  .github/workflows/build-test-measure.yml
Labels: dependencies, infrastructure
